import random

behavioral_questions = [
    "Tell me about yourself.",
    "Can you describe a time when you had to overcome a challenge?",
    "How do you handle stress and pressure?",
    "Give an example of a goal you reached and how you achieved it.",
    "Describe a situation where you showed leadership.",
    "Have you ever had to work with a difficult colleague? How did you handle it?",
    "Tell me about a time you made a mistake. How did you handle it?",
    "How do you prioritize your tasks when dealing with tight deadlines?",
    "Describe a situation where you had to collaborate with a team to achieve a goal.",
    "How do you handle feedback or criticism?",
    "Tell me about a time you failed and how you overcame it.",
    "Give an example of how you’ve worked on a team.",
    "Describe a time when you disagreed with a coworker. How was the issue resolved?",
    "How do you stay organized when working on multiple projects?",
    "Have you ever gone above and beyond for a project or task?",
    "Tell me about a time when you had to take the lead on a project.",
    "Describe a time you solved a difficult problem.",
    "Give an example of a time when you worked well under pressure.",
    "Tell me about a time when you were able to improve a process.",
    "How do you manage competing priorities in your work?",
    "Describe a time when you had to adapt to a significant change.",
    "Tell me about a time you handled a difficult customer.",
    "How do you handle failure or setbacks?",
    "Can you tell me about a time when you had to work with limited resources?",
    "Have you ever had to motivate a team? How did you do it?",
    "Describe a time you had to make a difficult decision.",
    "Tell me about a time you took a risk and what the outcome was.",
    "How do you handle ambiguity in your work?",
    "Give an example of a time when you had to manage a conflict.",
    "Describe a time you had to work with someone whose personality was very different from yours.",
    "How do you handle situations where you don’t know the answer?",
    "Tell me about a time you had to learn something new quickly.",
    "Have you ever had to persuade someone to see things your way? How did you do it?",
    "Describe a time when you showed initiative.",
    "Can you provide an example of how you handled a difficult project?",
    "Tell me about a time you disagreed with your boss.",
    "How do you manage tight deadlines?",
    "Give an example of a time you improved efficiency in a project.",
    "Describe a time when you dealt with a challenging situation in the workplace.",
    "How do you handle a situation when you have to deliver bad news?",
    "Have you ever had to work on a project with a team where there were conflicting opinions? How did you handle it?",
    "Describe a time when you had to go above and beyond to complete a task.",
    "Give an example of a time when you had to deal with a difficult customer or client.",
    "Tell me about a time you managed a project. How did you ensure it was successful?",
    "Describe a time when you had to meet a tight deadline.",
    "How do you handle conflict in a team environment?",
    "Give an example of how you managed a work-life balance during a busy period.",
    "Tell me about a time you made a mistake and how you handled it.",
    "Describe a situation where you had to be creative to solve a problem.",
    "How do you manage competing priorities in a team setting?",
    "Tell me about a time you handled an unexpected challenge.",
    "Have you ever worked on a project that didn't go as planned? How did you respond?",
    "Describe a time you had to manage multiple deadlines.",
    "Give an example of a time when you had to work without clear instructions.",
    "Tell me about a time you had to manage your time effectively.",
    "Describe a time when you had to present a solution to a problem to senior management.",
    "Have you ever had to manage a conflict between team members?",
    "Tell me about a time you had to learn a new skill quickly.",
    "Describe a time when you took the initiative to improve something at work.",
    "How do you handle constructive feedback?",
    "Tell me about a time you had to manage a project with limited resources.",
    "Have you ever faced an ethical dilemma at work? How did you handle it?",
    "Describe a situation where you had to mentor or coach someone.",
    "How do you handle situations where you are not sure what the right course of action is?",
    "Tell me about a time you had to resolve a conflict with a customer.",
    "Have you ever had to deal with a sudden change in priorities? How did you manage it?",
    "Give an example of a time when you had to manage a difficult stakeholder.",
    "Tell me about a time when you exceeded expectations on a project.",
    "How do you handle repetitive or mundane tasks?",
    "Describe a time when you successfully managed a team through a stressful project.",
    "Have you ever been in a situation where you had to deliver a difficult message to a colleague?",
    "Tell me about a time when you had to delegate tasks effectively.",
    "Describe a time when you had to work on a task outside of your comfort zone.",
    "How do you handle long-term projects that require consistent effort?",
    "Give an example of how you dealt with a major setback.",
    "Tell me about a time when you had to deal with a difficult deadline.",
    "Describe a time you had to work under unclear guidelines or instructions.",
    "Have you ever had to manage multiple stakeholders with competing interests?",
    "Tell me about a time when you had to build consensus in a team setting.",
    "How do you handle feedback that you don’t agree with?",
    "Describe a time when you had to lead a team through a difficult challenge.",
    "Give an example of a time when you had to make a tough decision without all the information.",
    "Tell me about a time when you had to adapt to a new role or responsibility.",
    "Describe a situation where you had to take ownership of a project.",
    "How do you approach continuous learning and development?",
    "Tell me about a time when you had to manage a large workload with minimal supervision.",
    "Describe a time when you worked in a cross-functional team.",
    "Give an example of a time when you handled an unexpected problem at work.",
    "Tell me about a time when you had to negotiate with a difficult stakeholder.",
    "How do you handle projects with changing requirements?",
    "Describe a time when you had to provide constructive feedback to a team member.",
    "Tell me about a time when you had to work under high pressure.",
    "Have you ever had to manage a project where priorities changed suddenly? How did you adapt?",
    "Describe a time when you had to collaborate with a team that was geographically dispersed.",
    "Tell me about a time when you had to push back against an unrealistic deadline.",
    "How do you handle ambiguity in project requirements?",
    "Describe a situation where you successfully managed a difficult customer interaction.",
    "Tell me about a time when you had to quickly build rapport with a new team.",
    "Have you ever worked in a situation where there was a lack of clear direction?",
    "Tell me about a time when you had to step up and take responsibility for a project’s success or failure.",
    "Describe a time when you had to manage multiple competing priorities.",
    "Tell me about a time when you had to meet a goal with limited time and resources.",
    "Describe a situation where you had to convince others to make a change.",
    "Have you ever handled a situation where you had to switch priorities mid-task?",
    "Tell me about a time when you led a group project and the results.",
    "How do you approach problem-solving in your daily work?",
    "Can you tell me about a time you had to mentor a colleague?",
    "Give an example of a time you managed competing priorities.",
    "How do you handle pressure when managing a high-stakes project?",
    "Tell me about a situation where you had to use your communication skills to influence someone’s opinion.",
    "Describe a situation when you helped a team achieve its goals.",
    "Tell me about a time you had to learn from failure.",
    "Describe a time you took initiative to resolve a problem.",
    "Give an example of how you handled a disagreement with a supervisor.",
    "Tell me about a time when you managed a project that required a lot of attention to detail.",
    "Describe a time when you had to resolve a conflict among team members.",
    "Can you provide an example of a decision you made that was unpopular? How did you handle it?",
    "Tell me about a time you worked on a project outside your area of expertise.",
    "Describe a time you had to lead a team under challenging circumstances.",
    "Have you ever received negative feedback? How did you respond to it?",
    "Tell me about a time when you disagreed with your team and how you handled it.",
    "How do you handle competing deadlines?",
    "Describe a time when you had to deal with a sudden crisis or emergency at work.",
    "Give an example of a time you had to step in to resolve an issue without being asked.",
    "How do you manage stress during peak periods at work?",
    "Tell me about a time when you had to challenge the status quo.",
    "Describe a time when you had to deliver a tough message to your team.",
    "Have you ever been involved in resolving a customer complaint? How did you handle it?",
    "Tell me about a situation where you had to manage a sensitive issue.",
    "Describe a time when you managed a team with diverse skill sets and experiences.",
    "Give an example of a time when you made a mistake and how you corrected it.",
    "Tell me about a time when you had to motivate a demotivated team member.",
    "Describe a time when you had to make a decision with incomplete information.",
    "How do you manage deadlines when you’re also responsible for day-to-day work?",
    "Tell me about a situation where you had to coordinate multiple projects.",
    "Describe a time when you had to influence others who were not direct reports.",
    "Give an example of how you’ve dealt with a major change in your work environment.",
    "Tell me about a time when you had to adapt to a major change.",
    "How do you approach building rapport with new colleagues?",
    "Describe a situation where you had to make a difficult choice between competing projects.",
    "Give an example of a time when you had to deal with a colleague who was not contributing to a team effort.",
    "Tell me about a time when you had to take charge in an unexpected situation.",
    "Describe a time when you had to make a quick decision in a high-pressure situation.",
    "Have you ever had to implement a new process that you did not fully agree with? How did you handle it?",
    "Tell me about a time when you had to work with a cross-functional team.",
    "Describe a situation where you went out of your way to solve a problem.",
    "Give an example of a time when you had to handle a difficult client or customer.",
    "How do you handle repetitive tasks while maintaining motivation?",
    "Tell me about a time when you had to take responsibility for a mistake that impacted others.",
    "Describe a time when you had to implement a creative solution to solve a problem.",
    "Tell me about a time when you had to take accountability for a project's success.",
    "Give an example of a time when you successfully delegated tasks.",
    "Describe a time when you had to manage a team through change.",
    "How do you approach situations where there is a lack of structure?",
    "Tell me about a time when you had to make a decision that impacted multiple stakeholders.",
    "Describe a time when you had to mediate a conflict between two coworkers.",
    "Give an example of how you handled a difficult decision with little guidance.",
    "Tell me about a time when you turned a negative situation into a positive outcome.",
    "Describe a time when you had to give constructive feedback to a colleague.",
    "How do you approach problem-solving when the solution is not obvious?",
    "Tell me about a time when you had to make a significant decision under tight deadlines.",
    "Describe a time when you had to manage competing requests from stakeholders.",
    "Have you ever worked on a team where someone wasn’t pulling their weight? How did you address it?",
    "Tell me about a time when you had to present a controversial idea to a group.",
    "Describe a time when you had to manage a client’s expectations.",
    "How do you handle situations where you have to take on additional responsibilities?",
    "Tell me about a time when you successfully implemented a new strategy.",
    "Describe a time when you had to troubleshoot an unexpected issue.",
    "Have you ever worked on a project where the goals changed midway? How did you adapt?",
    "Tell me about a time when you had to manage a remote team.",
    "Describe a situation where you went beyond your job description to get the work done.",
    "How do you handle criticism from your manager or peers?",
    "Tell me about a time when you had to manage a project with little guidance.",
    "Describe a time when you had to resolve a technical problem.",
    "How do you handle situations where the project scope keeps expanding?",
    "Tell me about a time when you worked with a difficult client or vendor.",
    "Describe a time when you had to lead a team through a challenging project.",
    "How do you handle projects that require cooperation from people outside of your team?",
    "Tell me about a time when you had to make a trade-off between quality and time.",
    "Describe a time when you had to learn a new tool or technology quickly.",
    "Tell me about a time when you had to support a team member who was struggling.",
    "How do you approach decision-making when dealing with multiple unknowns?",
    "Tell me about a time when you successfully managed a high-profile project.",
    "Describe a time when you worked on a project with conflicting priorities.",
    "Give an example of a time when you had to influence someone in a position of power.",
    "Tell me about a time when you had to handle a complex situation with limited resources.",
    "Describe a time when you had to manage multiple stakeholders' expectations.",
    "Tell me about a time when you had to deal with a sudden setback.",
    "Describe a time when you had to take a calculated risk in your work.",
    "How do you approach continuous improvement in your work?",
    "Tell me about a time when you had to coach a colleague through a difficult task.",
    "Describe a time when you had to take on a leadership role unexpectedly.",
    "Tell me about a time when you implemented a solution that saved time or money.",
    "Describe a time when you had to work on a project where you lacked technical knowledge.",
    "How do you handle competing interests in a project?",
    "Tell me about a time when you had to develop a new skill in a short period.",
    "Describe a time when you had to negotiate a solution that benefited both sides.",
    "Tell me about a time when you had to push back on a decision you disagreed with.",
    "How do you manage long-term projects that require sustained attention?",
    "Tell me about a time when you had to take the lead on a high-visibility project."
]


def bq_select():
  return random.choice(behavioral_questions)